---
services:
 - docker:dind
stages:
 - linting
 - build_and_push
variables:
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  TTY: xterm
cache:
  paths:
    - .cache/
    - venv/
.linting: &linting
   stage: linting
dockerfile_lint:
   <<: *linting
   image: hadolint/hadolint:latest-debian
   before_script:
      - hadolint --version
   script:
      - hadolint --config .hadolint.yaml ./Dockerfile
build_dockerfiles:
  variables:
    DOCKER_DRIVER: overlay2
  stage: build_and_push
  before_script:
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - sudo make docker-image
    - docker pull $CONTAINER_IMAGE:latest
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:$CI_COMMIT_SHA -t $CONTAINER_IMAGE:$CI_BUILD_REF -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
