---
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  TTY: xterm

stages:
 - linting
 - build
 - push
 
before_script:
  - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"

.linting: &linting
   stage: linting
dockerfile_lint:
   <<: *linting
   image: hadolint/hadolint:latest-debian
   script:
      - hadolint --config .hadolint.yaml ./Dockerfile

.build: &build
  stage: build
build:
  <<: *build
  script:
    - sudo make docker-image
.push: &push
  stage: push
push:
  <<: *push
  script:
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CONTAINER_IMAGE:$CI_BUILD_SHA