version: '3.7'

services:
  ansible-arch:
    image: registry.gitlab.com/sultangillani/ansible-docker-archlinux:latest
    build:
      context: archlinux
    stdin_open: true
    tty: true
    container_name: ansible-arch
